# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do |options|
  desc "archive and export"

  lane :beta do


 #  	increment_version_number(
 #  		version_number: options[:app_version],
 #  		xcodeproj: './Mooyaho iOS/MooyahoApp.xcodeproj'
	# )

	# increment_build_number_in_xcodeproj(
	# 	xcodeproj: './Mooyaho iOS/MooyahoApp.xcodeproj',
	# 	build_number: options[:build_number],
	# 	build_configuration_name: 'Release'
	# )

	build_app(
		workspace: "Clean-Mooyaho-Codebase.xcworkspace",
		configuration: "Release",
		scheme: "Mooyaho iOS",
		clean: true,
		export_method: "development",
		include_bitcode: false,
		output_name: "sample.ipa",
		export_options: {
			provisioningProfiles: {
				"com.sudo.park.Mooyaho-iOS" => "match AppStore com.sudo.park.Mooyaho-iOS"
			}
		}
	)    
  end
end
